version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosec:
    excludes:
      - G104  # audit use of unsafe
  govet:
    enable:
      - shadow

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - staticcheck
